server:
  port: 8000
spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.10:8848
        namespace: public
        group: DEFAULT_GROUP
      server-addr: 192.168.10.10
#      server-addr: 101.34.84.152:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}


logging:
  level:
    com.atguigu.order.feign: debug



#进行多文档的部署模式,如果当前的profile.active=dev就会进行激活下面的配置
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev