spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
            ##重试器的配置
#            retryer: feign.retryer.Default #使用OpenFeign的默认的重试器的配置
#            #下面的服务名是OpenFeignclient中进行指定的服务的名字
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#    sentinel:
#      transport:
##        dashboard: 192.168.10.10:8858
#      dashboard: 101.34.84.152:8858
#      eager: true #提前进行加载连接sentinel控制台
    sentinel:
      transport:
        dashboard: 101.34.84.152:8858
        port: 8719  # 默认端口，或者手动指定一个可用端口
      eager: true

feign:
  sentinel:
    enabled: true
