server:
  port: 80

spring:
  application:
    name: gateway
  profiles:
    include: route
  cloud:
    nacos:
      server-addr: 192.168.10.10:8848


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
